apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manuela-deployment
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nexus-Six/edge_anomaly_detection_demo.git
    targetRevision: main
    path: config/instances/manuela-quickstart/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
