apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- route.yaml
- messaging-deployment.yaml

resources:
- amq-operator-subscription.yaml

bases:
#- github.com/sa-mw-dach/manuela-gitops/config/templates/manuela/messaging
- ../../../templates/manuela-openshift/messaging
#- ../../../templates/installplan-approver

images:
- name: messaging
  newName: quay.io/nexus6/edge-anomaly-detection-consumer
  newTag: latest

